Get credentials

diff --git a/.github/workflows/delete.yml b/.github/workflows/delete.yml
--- a/.github/workflows/delete.yml
+++ b/.github/workflows/delete.yml
@@ -4,41 +4,59 @@ on:
   workflow_dispatch
 
 jobs:
-  delete-resources:
+  build:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Check out code
-      uses: actions/checkout@v2
+      - name: Checkout Code
+        uses: actions/checkout@v2
 
-    - name: Set up kubectl
-      uses: azure/k8s-set-context@v1
-      with:
-        kubeconfig: ${{ secrets.KUBECONFIG }}
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.x
 
-    - name: Delete Deployments
-      run: |
-        kubectl delete deployment hasher-deployment -n teoschool
-        kubectl delete deployment redis-deployment -n teoschool
-        kubectl delete deployment rng-deployment -n teoschool
-        kubectl delete deployment webui-deployment -n teoschool
-        kubectl delete deployment worker-deployment -n teoschool
-        kubectl delete deploy prometheus-deployment -n teoschool
-        kubectl delete deploy grafana-deployment -n teoschool
+      - name: Check and Install Az CLI
+        run: |
+          if ! command -v az &> /dev/null
+          then
+            echo "Az CLI not found. Installing..."
+            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+          fi
+        shell: bash
 
-    - name: Delete Services
-      run: |
-        kubectl delete service hasher -n teoschool
-        kubectl delete service redis -n teoschool
-        kubectl delete service rng -n teoschool
-        kubectl delete service webui-service -n teoschool
-        kubectl delete service grafana-service -n teoschool
-        kubectl delete service prometheus-service -n teoschool
-    
-    - name: Delete configMap
-      run: |
-        kubectl delete configMap prometheus-config -n teoschool
-    
-    - name: Delete namespace
-      run: |
-        kubectl delete namespace teoschool
+      - name: Login to Azure
+        id: azure_login
+        uses: azure/login@v1
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+
+      - name: Get credentials
+        run: az aks get-credentials --resource-group re-teoSchool-djiby --name aks-djiby
+        
+      - name: Delete Deployments
+        run: |
+          kubectl delete deployment hasher-deployment -n teoschool
+          kubectl delete deployment redis-deployment -n teoschool
+          kubectl delete deployment rng-deployment -n teoschool
+          kubectl delete deployment webui-deployment -n teoschool
+          kubectl delete deployment worker-deployment -n teoschool
+          kubectl delete deploy prometheus-deployment -n teoschool
+          kubectl delete deploy grafana-deployment -n teoschool
+
+      - name: Delete Services
+        run: |
+          kubectl delete service hasher -n teoschool
+          kubectl delete service redis -n teoschool
+          kubectl delete service rng -n teoschool
+          kubectl delete service webui-service -n teoschool
+          kubectl delete service grafana-service -n teoschool
+          kubectl delete service prometheus-service -n teoschool
+      
+      - name: Delete configMap
+        run: |
+          kubectl delete configMap prometheus-config -n teoschool
+      
+      - name: Delete namespace
+        run: |
+          kubectl delete namespace teoschool
